"use client";
import { AlternativeKey, Question } from "@/lib/types";
import AlternativeButton from "./AlternativeButton";
import FeedbackPanel from "./FeedbackPanel";

export default function QuestionCard(props: { question: Question; index: number; selected: AlternativeKey | null; striked: AlternativeKey[]; answered: boolean; locked: boolean; finished: boolean; onSelect: (a: AlternativeKey) => void; onToggleStrike: (a: AlternativeKey) => void; onAnswer: () => void; onUnlock: () => void; }) {
  const { question, index, selected, striked, answered, locked, finished, onSelect, onToggleStrike, onAnswer, onUnlock } = props;
  const canAnswer = !locked && !finished && !!selected;

  return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="mb-3 flex flex-wrap gap-2 text-xs"><span className="rounded-full bg-slate-100 px-2 py-1">Questão {index + 1}</span>{question.disciplina ? <span className="rounded-full bg-indigo-100 px-2 py-1 text-indigo-900">{question.disciplina}</span> : null}{question.tema ? <span className="rounded-full bg-purple-100 px-2 py-1 text-purple-900">{question.tema}</span> : null}</div><p className="mb-4 whitespace-pre-line text-slate-800">{question.enunciado}</p><div className="space-y-2">{(["A", "B", "C", "D"] as AlternativeKey[]).map((k) => <AlternativeButton key={k} label={k} text={question.alternativas[k]} selected={selected === k} striked={striked.includes(k)} locked={locked && !finished} correct={(answered || finished) && question.correta === k} wrong={(answered || finished) && selected === k && selected !== question.correta} onSelect={() => onSelect(k)} onToggleStrike={() => onToggleStrike(k)} />)}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row sm:items-center">{!locked && !finished ? <button onClick={onAnswer} disabled={!canAnswer} className={`rounded-xl px-4 py-2 text-white transition-all ${canAnswer ? "bg-blue-600 hover:bg-blue-700" : "cursor-not-allowed bg-slate-400 opacity-60"}`}>Responder</button> : null}{!canAnswer && !locked && !finished ? <span className="text-sm text-slate-500">Selecione uma alternativa para responder.</span> : null}{locked && !finished ? <button onClick={onUnlock} className="rounded-xl bg-amber-500 px-4 py-2 text-white transition-all hover:bg-amber-600">Alterar resposta</button> : null}</div>{(answered || finished) ? <FeedbackPanel question={question} selected={selected} /> : null}</div>;
}
